export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  ADD_ADMIN: "ADD_ADMIN",
  DELETE_ADMIN: "DELETE_ADMIN",
  EDIT_ADMIN: "EDIT_ADMIN",
  SET_ADMINS: "SET_ADMINS",
  SELECTED_ADMIN: "SELECTED_ADMIN",
};
